---
- name: Configuro servidor base de datos en ubuntu
  hosts: database
  become: true
  user: sadmin

  task:
  
  - name: UFW instalado
    ansible.builtin.apt:
      name: ufw
      state: present

  - name: Permitir puerto 22 en UFW
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: Defino politicas de trafico entrante
    community.general.ufw:
      policy: allow
      direction: incoming
      state: enabled

  - name: Defino politicas de trafico saliente
    community.general.ufw:
      policy: deny
      direction: outgoing
      state: enabled
  
  - name: Servicio UFW levantado y activo
    ansible.builtin.systemd_service:
      name: ufw
      state: started
      enabled: true
  
## Instalacion de base de datos
  - name: MariaDB instalado
    ansible.builyin.apt:
      name: mariadb-server
      state: present
      update-cache: true
      
  - name: Servidor Mariadb levantado
    ansible.builtin.systemd_service:
      name: mariadb
      state: started
      enabled: true
      
  - name: Habilitamos en ufw la conexion a mariadb
    community.general.ufw:
      rule: allow
      port: '3306'
      protocol: tcp
      direction: in
      
##  Configuracion de base de datos

  - name: Creo la base de datos todo
    community.mysql.mysql_db:
      check_implicit_admin: true
      login_host: "{{ hostvars[inventory_hostname].ansible_host }}"
      login_user: root
      login_password: dbadmin
      name: todo
      state: present
    delegate_to: localhost
    connection: local
      
