---
- name: Configuro servidor base de datos en ubuntu
  hosts: database
  become: true
  user: sadmin

  task:
  
  - name: UFW instalado
    ansible.builtin.apt:
      name: ufw
      state: present

  - name: Permitir puerto 22 en UFW
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: Defino politicas de trafico entrante
    community.general.ufw:
      policy: "{{ item.value }}"
      direction: "{{ item.key }}"
      state: enabled
    loop:
      - in: deny
      - out: allow

  - name: Servicio UFW levantado y activo
    ansible.builtin.systemd_service:
      name: ufw
      state: started
      enabled: true
  
## Configuracion de base de datos
  - name: MariaDB instalado
    ansible.builyin.apt:
      name: mariadb-server
      state: present
      update-cache: true
      
  - name: Servidor Mariadb levantado
    ansible.builtin.systemd_service:
      name: mariadb
      state: started
      enabled: true

##       
      
