---
- name: Configurar base de datos MySQL
  hosts: database
  become: true
  user: sysadmin

  tasks:

    - name: Crear el usuario root y otorgar permisos
      ansible.builtin.shell: |
        mysql -u root -p'root_password' -e "CREATE USER 'root'@'%' IDENTIFIED BY 'new_password';"
        mysql -u root -p'root_password' -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"
        mysql -u root -p'root_password' -e "FLUSH PRIVILEGES;"
      args:
        executable: /bin/bash
      environment:
        MYSQL_PWD: dbadmin

    - name: Crear base de datos todo
      ansible.builtin.shell: |
        mysql -u root -p'new_password' -e "CREATE DATABASE IF NOT EXISTS todo;"
      args:
        executable: /bin/bash
      environment:
        MYSQL_PWD: dbadmin

    - name: Copiar archivo SQL al servidor
      ansible.builtin.copy:
        src: ./files/todo.sql
        dest: /tmp/todo.sql

    - name: Importar archivo SQL
      ansible.builtin.shell: |
        mysql -u root -p'new_password' -e todo < /tmp/todo.sql
      args:
        executable: /bin/bash
      environment:
        MYSQL_PWD: dbadmin

## Creo usuarios y los muestro al final para verificar:

    - name: Agregar usuarios de prueba a la base de datos
      ansible.builtin.shell: |
        mysql -u root -p'new_password' -e "
        USE todo;
        INSERT INTO users (first_name, last_name, username, password) VALUES ('John', 'Doe', 'jdoe', 'password123');
        INSERT INTO users (first_name, last_name, username, password) VALUES ('Jane', 'Smith', 'jsmith', 'password456');
        INSERT INTO users (first_name, last_name, username, password) VALUES ('Alice', 'Johnson', 'ajohnson', 'password789');
        "
      args:
        executable: /bin/bash
      environment:
        MYSQL_PWD: dbadmin

    - name: Consultar y mostrar los usuarios creados
      ansible.builtin.shell: |
        mysql -u root -p'new_password' -e "
        USE todo;
        SELECT * FROM users;
        "
      args:
        executable: /bin/bash
      environment:
        MYSQL_PWD: dbadmin
      register: query_result

    - name: Mostrar resultado de la consulta
      ansible.builtin.debug:
        var: query_result.stdout