---
- name: Instalar y configurar la aplicaci贸n ToDo en CentOS 9
  hosts: webserver
  become: true
  user: sysadmin

  vars:
    db_user: "sysadmin"
    db_password: "tlxadmin"
    db_host: "localhost"
    db_name: "DatabaseTSL"

  tasks:

    ## Primero instalo JAVA
    - name: Instalo el JAVA SDK
      ansible.builtin.yum_repository:
        name: java-1.8.0-openjdk
        state: present

      ## Segundo bajo y extraigo el Tomcat
    - name: Bajo el Tomcat y extrae en el directorio /opt/.
      ansible.builtin.yum_repository:
        name: tomcat
        state: present

    - name: Iniciar y habilitar Tomcat service
      ansible.builtin.systemd_service:
        name: tomcat
        state: started
        enabled: yes

      ## Tercero abro puertos necesarios
    - name: Habilitar puerto 8080 en el firewall para Tomcat
      ansible.posix.firewalld:
        port: 8080/tcp
        state: enabled
        immediate: yes
        permanent: yes

    - name: Habilitar puerto 8443 en el firewall para Tomcat
      ansible.posix.firewalld:
        port: 8443/tcp
        state: enabled
        immediate: yes
        permanent: yes   

      ## Despliego app todo.war
    - name: Copiar la aplicaci贸n ToDo a directorio de Tomcat
      ansible.builtin.copy:
        src: ./files/todo.war
        dest: /var/lib/tomcat/webapps/todo.war

      ## cargo la configuraci贸n de todo.war
    - name: Configurar la base de datos en la aplicaci贸n ToDo
      ansible.builtin.template:
        src: ./files/todo_db_config.xml.j2
        dest: /var/lib/tomcat/conf/Catalina/localhost/todo.xml

    - name: Reiniciar Tomcat para desplegar todo
      ansible.builtin.systemd_service:
        name: tomcat
        state: restarted