---
- name: Instalar y configurar un webserver
  hosts: centos
  become: true
  user: sadmin

  tasks:

  - name: Instalar apache
    ansible.builtin.dnf:
      name: httpd
      state: present

  - name: Configurar virtualhost
    ansible.builtin.copy: 
      src: ./files/virtualhost.conf
      dest: /etc/httpd/conf.d
    notify: Reiniciar apache

  - name: Crear directorio document root
    ansible.builtin.file:
      path: /var/www/ejemplo/html
      state: directory
      mode: '0755'
      owner: apache
      group: apache
      
  - name: Copiar pagina del sitio
    ansible.builtin.template:
      src: ./templates/index.j2
      dest: /var/www/ejemplo/html/index.html
      owner: apache
      group: apache
      mode: '0644'

  - name: Permitir conexiones a los puertos 80 y 443
    ansible.posix.firewalld:
      service: "{{ item }}"
      state: enabled
      immediate: true
      permanent: true
    with_items:
      - http
      - https

  - name: Apache levantado y habilitado
    ansible.builtin.systemd_service:
      name: httpd
      state: started
      enabled: true      

  handlers:

  - name: Reiniciar apache
    ansible.builtin.systemd_service:
      name: httpd
      state: restarted

  
