---
- name: Hardening de servidores linux
  hosts: linux
  become: true
  user: sysadmin

  tasks:

  - name: Configuro opciones de seguridad de ssh
    ansible.builtin.lineinfile: 
      path: /etc/ssh/sshd_config
      regexp: '^#PermitRootLogin'
      line: PermitRootLogin no
    notify: Reinicio servidor ssh
    register: results_sshd
    
  - name: Inyecto la clave publica SSH en los servidores
    ansible.posix.authorized_key:
      user: sadmin
      state: present
      key: "{{ lookup('file', '/home/sadmin/.ssh/id_rsa.pub') }}"

  - name: Ver resultado de tarea anterior
    ansible.builtin.debug:
      var: results_sshd
  
  handlers:

  - name: Reinicio servidor ssh
    ansible.builtin.systemd_service:
      name: "{{ ssh_service }}"
      state: restarted