---
- name: Instalar y configurar la aplicación ToDo en CentOS 9
  hosts: centos
  become: true
  user: sysadmin

  vars:
    db_user: "sysadmin"
    db_password: "dbadmin"
    db_host: "192.168.56.104"
    db_name: "DatabaseTSL"

  tasks:

    ## Primero instalo JAVA
    - name: Instalo el JAVA SDK
      yum:
        name: java-1.8.0-openjdk
        state: present

      ## Segundo bajo y extraigo el Tomcat
    - name: Bajo el Tomcat y extrae en el directorio /opt/.
      yum:
        name: tomcat
        state: present

    - name: Iniciar y habilitar Tomcat service
      systemd:
        name: tomcat
        state: started
        enabled: yes

      ## Tercero abro puertos necesarios
    - name: Habilitar puerto 8080 en el firewall para Tomcat
      ansible.posix.firewalld:
        port: 8080/tcp
        state: enabled
        immediate: yes
        permanent: yes

    - name: Habilitar puerto 8443 en el firewall para Tomcat
      ansible.posix.firewalld:
        port: 8443/tcp
        state: enabled
        immediate: yes
        permanent: yes   

      ## Despliego app todo.war
    - name: Copiar la aplicación ToDo a directorio de Tomcat
      ansible.builtin.copy:
        src: ./Files/todo.war
        dest: /var/lib/tomcat/webapps/todo.war

      ## verifico que exista un directorio donde cargar la configuración de todo.war
    - name: Crear directorio para la configuración de Tomcat si no existe
      ansible.builtin.file:
        path: /var/lib/tomcat/conf/Catalina/localhost
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0755'

      ## cargo la configuración de todo.war
    - name: Configurar la base de datos en la aplicación ToDo
      ansible.builtin.template:
        src: ./Template/todo_db_config.xml.j2
        dest: /var/lib/tomcat/conf/Catalina/localhost/todo.xml

    - name: Reiniciar Tomcat para desplegar todo
      ansible.builtin.systemd_service:
        name: tomcat
        state: restarted
